jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: CmdLine@2
    displayName: 'Install Depot Tools'
    inputs:
      script: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
         setx path "%path%;$(Build.SourcesDirectory)\depot_tools\"
         ./depot_tools/gclient.bat

  - task: CmdLine@2
    displayName: 'Prepare Sources'
    inputs:
      script: |
        python scripts/bootstrap.py
        ./depot_tools/gclient.bat sync
    
  - task: CmdLine@2
    displayName: 'Generate Ninja'
    inputs:
      script: |
        gn gen out/Release



