# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- avalonia-fork-master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: CmdLine@2
    displayName: 'Install Depot Tools'
    inputs:
      script: |
         git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
         pathman /as ./depot_tools
         gclient

