jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: CmdLine@2
    displayName: 'Install Depot Tools'
    inputs:
      script: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
         setx path "%path%;$(Build.SourcesDirectory)"
         gclient
