<Project>
    <PropertyGroup>
        <StaticAvaloniaAngleLinking Condition=" '$(StaticAvaloniaAngleLinking)' == '' ">false</StaticAvaloniaAngleLinking>
        
        <_AngleBinariesRuntimePath Condition="$(RuntimeIdentifier.StartsWith('win')) and $(RuntimeIdentifier.EndsWith('x64'))">$(MSBuildThisFileDirectory)\runtimes\win-x64\native</_AngleBinariesRuntimePath>
        <_AngleBinariesRuntimePath Condition="$(RuntimeIdentifier.StartsWith('win')) and $(RuntimeIdentifier.EndsWith('x86'))">$(MSBuildThisFileDirectory)\runtimes\win-x86\native</_AngleBinariesRuntimePath>
        <_AngleBinariesRuntimePath Condition="$(RuntimeIdentifier.StartsWith('win')) and $(RuntimeIdentifier.EndsWith('arm64'))">$(MSBuildThisFileDirectory)\runtimes\win-arm64\native</_AngleBinariesRuntimePath>
    </PropertyGroup>

    <ItemGroup Condition="'$(StaticAvaloniaAngleLinking)' == 'true' and '$(NativeLib)' != 'Static' and '$(_AngleBinariesRuntimePath)' != ''">
      <NativeLibrary Include="$(_AngleBinariesRuntimePath)\av_libglesv2.lib" />
      <DirectPInvoke Include="av_libglesv2" />
    </ItemGroup>
</Project>